### ISSUE TITLE
maltrail plugin issue @ 19.7 production

### ISSUE THREAD

**Issue by hippi-viking** [opnsense/plugins#1417]
Hello,

Just upgraded to 19.7 production (thanks for the great work!), and decided to give the maltrail plugin a try.
Upon starting it the status indicator turns red no matter the settings i enter in the gui. Trying to run server.py and sensor.py from console gave me the following errors:

yyy@xxx:/usr/local/share/maltrail % python2.7 server.py
Traceback (most recent call last):
  File "server.py", line 24, in <module>
    from core.common import check_connection
  File "/usr/local/share/maltrail/core/common.py", line 12, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
yyy@xxx:/usr/local/share/maltrail % python2.7 sensor.py 
Traceback (most recent call last):
  File "sensor.py", line 35, in <module>
    from core.common import check_connection
  File "/usr/local/share/maltrail/core/common.py", line 12, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

I suspect the reason might be some residual files/settings on the development machine that is not present on mine.

[edit]
Seems like sqlite3 is only installed for python3 but not for python2, that would explain why it is not working for me.

**Comment by mimugmail** [comment]
https://forum.opnsense.org/index.php?topic=13501.msg62237#msg62237
