### ISSUE TITLE
net/haproxy: session sync (peers)

### ISSUE THREAD

**Issue by fbrendel** [opnsense/plugins#165]
Hi,

it would be nice if the HAProxy plugin could synchronize the stick table to other nodes.
Then we could do on-line maintenance or fail over without interrupting user sessions.
http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#3.5-peers

Many thanks
Frank

**Comment by fraenki** [comment]
Thanks for bringing this up. This is already on my list, I'll look into it. Maybe we'll have this working in time for OPNsense 17.7 (ETA; no promises).

**Comment by fbrendel** [comment]
Sounds good. :smile:

**Comment by fraenki** [comment]
@fbrendel I have split these two features into their own issues.

**Comment by fraenki** [comment]
Session sync will be available in our plugin version 2.4.

@fbrendel I'd be glad if you could test this new feature and provide some feedback regarding it's current implementation.

**Comment by fbrendel** [comment]
Good news!
I'll test it and tell you how it works.
Thank you :smile:

**Comment by fbrendel** [comment]
The installation of the plugin shows some errors. Reloading the template seems to be OK.

```
# pkg install os-haproxy-devel-2.4.txz                                                                               
Updating OPNsense repository catalogue...                                                                                            
OPNsense repository is up to date.                                                                                                   
All repositories are up to date.                                                                                                     
The following 3 package(s) will be affected (of 0 checked):                                                                          
                                                                                                                                     
New packages to be INSTALLED:                                                                                                        
        os-haproxy-devel: 2.4                                                                                                        
        haproxy: 1.7.10                                                                                                              
        lua53: 5.3.4_2                                                                                                               
                                                                                                                                     
Number of packages to be installed: 3                                                                                                
                                                                                                                                     
The process will require 3 MiB more space.                                                                                           
750 KiB to be downloaded.                                                                                                            
                                                                                                                                     
Proceed with this action? [y/N]: y                                                                                                   
[1/3] Fetching haproxy-1.7.10.txz: 100%  567 KiB 580.4kB/s    00:01                                                                  
[2/3] Fetching lua53-5.3.4_2.txz: 100%  183 KiB 187.2kB/s    00:01                                                                   
Checking integrity... done (0 conflicting)                                                                                           
[3/3] Installing lua53-5.3.4_2...                                                                                                    
Extracting lua53-5.3.4_2: 100%                                                                                                       
[1/3] Installing haproxy-1.7.10...                                                                                                   
[1/3] Extracting haproxy-1.7.10: 100%                                                                                                
[2/3] Installing os-haproxy-devel-2.4...                                                                                             
[2/3] Extracting os-haproxy-devel-2.4: 100%                                                                                          
Stopping configd...done                                                                                                              
Starting configd.                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                           
Notice: Undefined variable: field_rfcls in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 137

Notice: Trying to get property of non-object in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 137

Fatal error: Uncaught OPNsense\Base\ModelException: class  of wrong type in model definition in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:137
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(168): OPNsense\Base\BaseModel->getNewField('OPNsense\\Base\\F...')
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(236): OPNsense\Base\BaseModel->parseXml(Object(SimpleXMLElement), NULL, Object(OPNsense\Base\FieldTypes\ContainerField))
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(236): OPNsense\Base\BaseModel->parseXml(Object(SimpleXMLElement), Object(SimpleXMLElement), Object(OPNsense\Base\FieldTypes\ContainerField))
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(287): OPNsense\Base\BaseModel->parseXml(Object(SimpleXMLElement), Object(SimpleXMLElement), Object(OPNsense\Base\FieldTypes\ContainerField))
#4 [internal function]: OPNsense\Base\BaseModel->__construct()
#5 /usr/local/opnsense/mvc/script/run_migrations.php(54): Reflec in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 137
Reloading template OPNsense/HAProxy: OK
```


But now I can't access the config page
```
Notice: Undefined variable: field_rfcls in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 137 Notice: Trying to get property of non-object in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 137 class of wrong type in model definition
```

**Comment by fraenki** [comment]
> But now I can't access the config page

It's not a bug in the plugin, it's a core issue. I'll get in contact with the developers.

**Comment by fichtner** [comment]
or at least opnsense-devel must be installed along with it...

**Comment by fbrendel** [comment]
With 18.1 it works now :grinning: 
```
root@tst1:~ # echo "show table TestPortalBackend" | socat /var/run/haproxy.socket stdio
# table: TestPortalBackend, type: string, size:51200, used:3
0x204adc1c904: key=fupy2dua01un230s2byb3sja use=0 exp=1795311 server_id=1
0x204adc1c844: key=jmbhddgz2qoni3zoc3erbv1s use=0 exp=1787591 server_id=2
0x204adc1c784: key=oygodasrmiaycdqwremduhhz use=0 exp=1764738 server_id=1

root@tst2:~ # echo "show table TestPortalBackend" | socat /var/run/haproxy.socket stdio
# table: TestPortalBackend, type: string, size:51200, used:3
0xc6a0a1c904: key=fupy2dua01un230s2byb3sja use=0 exp=1791200 server_id=1
0xc6a0a1c844: key=jmbhddgz2qoni3zoc3erbv1s use=0 exp=1783480 server_id=2
0xc6a0a1c784: key=oygodasrmiaycdqwremduhhz use=0 exp=1760628 server_id=1
```
Thank you!

**Comment by fichtner** [comment]
:)
