### ISSUE TITLE
Quagga/FRR Migration failed.

### ISSUE THREAD

**Issue by Xeroxxx** [opnsense/plugins#2018]
**Describe the bug**
Upgrading of templates for quagga/frr fails since atleast 20.1. I got this error on the major upgrade and every other upgrade of the package. Even on reinstallation.

```
Keep version OPNsense\Quagga\General (1.0.1)
Keep version OPNsense\Quagga\OSPF (1.0.4)
*** OPNsense\Quagga\OSPF6 Migration failed, check log for details
*** OPNsense\Quagga\RIP Migration failed, check log for details
*** OPNsense\Quagga\BGP Migration failed, check log for details
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Quagga: OK

```
**To Reproduce**
1. Upgrade or Uninstall/Install FRR Routing Package

**Expected behavior**
Templates upgrade and reload.

**Relevant log files**
`2020-09-06T23:10:29 | syslog-ng[98957] | Configuration reload finished;
-- | -- | --
2020-09-06T23:10:29 | syslog-ng[98957] | Configuration reload request received, reloading configuration;
2020-09-06T23:10:27 | config[30163] | #2 {main} )
2020-09-06T23:10:27 | config[30163] | #1 /usr/local/opnsense/mvc/script/run_migrations.php(57): OPNsense\Base\BaseModel->runMigrations()
2020-09-06T23:10:27 | config[30163] | #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(678): OPNsense\Base\BaseModel->serializeToConfig()
2020-09-06T23:10:27 | config[30163] | Stack trace:
2020-09-06T23:10:27 | config[30163] | in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:567
2020-09-06T23:10:27 | config[30163] | Model OPNsense\Quagga\BGP can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\BGP:asnumber] invalid integer value
2020-09-06T23:10:27 | config[30163] | [OPNsense\Quagga\BGP:asnumber] invalid integer value
2020-09-06T23:10:26 | config[30163] | #2 {main} )
2020-09-06T23:10:26 | config[30163] | #1 /usr/local/opnsense/mvc/script/run_migrations.php(57): OPNsense\Base\BaseModel->runMigrations()
2020-09-06T23:10:26 | config[30163] | #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(678): OPNsense\Base\BaseModel->serializeToConfig()
2020-09-06T23:10:26 | config[30163] | Stack trace:
2020-09-06T23:10:26 | config[30163] | in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:567
2020-09-06T23:10:26 | config[30163] | Model OPNsense\Quagga\RIP can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\RIP:networks] list validation error
2020-09-06T23:10:26 | config[30163] | [OPNsense\Quagga\RIP:networks] list validation error
2020-09-06T23:10:26 | config[30163] | #2 {main} )
2020-09-06T23:10:26 | config[30163] | #1 /usr/local/opnsense/mvc/script/run_migrations.php(57): OPNsense\Base\BaseModel->runMigrations()
2020-09-06T23:10:26 | config[30163] | #0 /usr/local/opnsense/mvc/app/models/OPNsen
`

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.1.a_69-amd64FreeBSD 12.1-RELEASE-p8-HBSDLibreSSL 3.1.4
Intel® Core™ i3-5020U 2.2GHz
Network Intel® I211-AT

**Comment by kpiq** [comment]
I get that when installing the FRR plugin in opnsense 20.7.2.   
FreeBSD psfwl01.lan 12.1-RELEASE-p7-HBSD FreeBSD 12.1-RELEASE-p7-HBSD #0  427d53bc125(stable/20.7)-dirty: Sun Jul 26 05:51:42 CEST 2020     root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64

**Comment by kpiq** [comment]
CPU: Intel(R) Atom(TM) CPU  E3845  @ 1.91GHz (1916.71-MHz K8-class CPU)
real memory  = 4294967296 (4096 MB)
avail memory = 3962900480 (3779 MB)
FreeBSD/SMP: Multiprocessor System Detected: 4 CPUs

**Comment by Xeroxxx** [comment]
Still fails with 21.1.3 - Development Branch.

**Comment by fraenki** [comment]
@fabianfrz Can you take care of this? It looks like the default settings are invalid, hence the migration will fail on new installs.

**Comment by Xeroxxx** [comment]
Maybe this helps:


2021-03-22T16:29:57 | configd.py[43133] | [f4248bc3-d943-4e5c-8808-29173ea1ec07] FRR diagnostics "show ipv6 ospf6 route json" |  
-- | -- | -- | --
2021-03-22T16:29:57 | configd.py[43133] | [0b1adeb3-f19b-47e0-9de9-a863bd110341] Script action failed with Command '/usr/local/opnsense/scripts/frr/legacy-diagnostics.py --ospfv3-database' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 479, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/frr/legacy-diagnostics.py --ospfv3-database' returned non-zero exit status 1. |  
2021-03-22T16:29:56 | configd.py[43133] | [0b1adeb3-f19b-47e0-9de9-a863bd110341] FRR diagnostics "show ipv6 ospf6 database json" |  
2021-03-22T16:29:56 | configd.py[43133] | [5a5911e4-9641-4e47-934b-7e235a2caeca] request quagga

After reinstall:

2021-03-22T16:32:52 | config[36247] | #2 {main} ) |  
-- | -- | -- | --
2021-03-22T16:32:52 | config[36247] | #1 /usr/local/opnsense/mvc/script/run_migrations.php(55): OPNsense\Base\BaseModel->runMigrations() |  
2021-03-22T16:32:52 | config[36247] | #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(686): OPNsense\Base\BaseModel->serializeToConfig() |  
2021-03-22T16:32:52 | config[36247] | Stack trace: |  
2021-03-22T16:32:52 | config[36247] | in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:575 |  
2021-03-22T16:32:52 | config[36247] | Model OPNsense\Quagga\BGP can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\BGP:asnumber] invalid integer value |  
2021-03-22T16:32:52 | config[36247] | [OPNsense\Quagga\BGP:asnumber] invalid integer value |  
2021-03-22T16:32:52 | config[36247] | #2 {main} ) |  
2021-03-22T16:32:52 | config[36247] | #1 /usr/local/opnsense/mvc/script/run_migrations.php(55): OPNsense\Base\BaseModel->runMigrations() |  
2021-03-22T16:32:52 | config[36247] | #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(686): OPNsense\Base\BaseModel->serializeToConfig() |  
2021-03-22T16:32:52 | config[36247] | Stack trace: |  
2021-03-22T16:32:52 | config[36247] | in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:575 |  
2021-03-22T16:32:52 | config[36247] | Model OPNsense\Quagga\RIP can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\RIP:networks] list validation error |  
2021-03-22T16:32:52 | config[36247] | [OPNsense\Quagga\RIP:networks] list validation error |  
2021-03-22T16:32:52 | config[36247] | #2 {main} ) |  
2021-03-22T16:32:52 | config[36247] | #1 /usr/local/opnsense/mvc/script/run_migrations.php(55): OPNsense\Base\BaseModel->runMigrations() |  
2021-03-22T16:32:52 | config[36247] | #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(686): OPNsense\Base\BaseModel->serializeToConfig() |  
2021-03-22T16:32:52 | config[36247] | Stack trace: |  
2021-03-22T16:32:52 | config[36247] | in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:575 |  
2021-03-22T16:32:52 | config[36247] | Model OPNsense\Quagga\OSPF6 can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\OSPF6:routerid] text validation error |  
2021-03-22T16:32:52 | config[36247] | [OPNsense\Quagga\OSPF6:routerid] text validation error

**Comment by Yoshi-081** [comment]
The issue i still present in 21.1.6

> New packages to be INSTALLED:

	frr7: 7.4_6
	libssh: 0.9.5
	libyang: 1.0.184
	net-snmp: 5.9_3,1
	os-frr: 1.21_3
	rtrlib: 0.6.3

> Number of packages to be installed: 6

> The process will require 30 MiB more space.
[1/6] Installing libssh-0.9.5...
[1/6] Extracting libssh-0.9.5: .......... done
[2/6] Installing libyang-1.0.184...
[2/6] Extracting libyang-1.0.184: .......... done
[3/6] Installing rtrlib-0.6.3...
[3/6] Extracting rtrlib-0.6.3: .......... done
[4/6] Installing net-snmp-5.9_3,1...
[4/6] Extracting net-snmp-5.9_3,1: .......... done
[5/6] Installing frr7-7.4_6...
===> Creating groups.
Creating group 'frr' with gid '168'.
Creating group 'frrvty' with gid '152'.
===> Creating users
Creating user 'frr' with uid '168'.
Adding user 'frr' to group 'frrvty'.
[5/6] Extracting frr7-7.4_6: .......... done
[6/6] Installing os-frr-1.21_3...
[6/6] Extracting os-frr-1.21_3: .......... done
Stopping configd...done
Starting configd.
Migrated OPNsense\Quagga\General from 0.0.0 to 1.0.2
Migrated OPNsense\Quagga\OSPF from 0.0.0 to 1.0.4
*** OPNsense\Quagga\OSPF6 Migration failed, check log for details
*** OPNsense\Quagga\RIP Migration failed, check log for details
*** OPNsense\Quagga\BGP Migration failed, check log for details
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Quagga: OK
Reloading template OPNsense/Syslog: OK

**Comment by mimugmail** [comment]
There is not a real problem, quite sure there are some fields marked as required but dont have a default

**Comment by Xeroxxx** [comment]
I think this is fixed, as I havent seen any migration errors anymore.

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/pull/2761
