### ISSUE TITLE
net/frr: 21.7.3_3 -> 21.7.4 causes config migration errors

### ISSUE THREAD

**Issue by g-a-c** [opnsense/plugins#2622]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
During the upgrade, I received two config migration errors from FRR, relating to OSPF and RIP. I don't use either of these setups, and I have no configuration for them, only BGP

```
*** OPNsense\Quagga\OSPF6 Migration failed, check log for details
*** OPNsense\Quagga\RIP Migration failed, check log for details
```

```
Oct 30 08:16:00 opnsense.home.arpa config[16762]: [2021-10-30T08:16:00+01:00][error] [OPNsense\Quagga\OSPF6:routerid] text validation error
Oct 30 08:16:00 opnsense.home.arpa config[16762]: [2021-10-30T08:16:00+01:00][error] Model OPNsense\Quagga\OSPF6 can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\OSPF6:routerid] text validation error
Oct 30 08:16:00 opnsense.home.arpa config[16762]:  in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:572
Oct 30 08:16:00 opnsense.home.arpa config[16762]: Stack trace:
Oct 30 08:16:00 opnsense.home.arpa config[16762]: #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(688): OPNsense\Base\BaseModel->serializeToConfig()
Oct 30 08:16:00 opnsense.home.arpa config[16762]: #1 /usr/local/opnsense/mvc/script/run_migrations.php(55): OPNsense\Base\BaseModel->runMigrations()
Oct 30 08:16:00 opnsense.home.arpa config[16762]: #2 {main} )
Oct 30 08:16:00 opnsense.home.arpa config[16762]: [2021-10-30T08:16:00+01:00][error] [OPNsense\Quagga\RIP:networks] list validation error
Oct 30 08:16:00 opnsense.home.arpa config[16762]: [2021-10-30T08:16:00+01:00][error] Model OPNsense\Quagga\RIP can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Quagga\RIP:networks] list validation error
Oct 30 08:16:00 opnsense.home.arpa config[16762]:  in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:572
Oct 30 08:16:00 opnsense.home.arpa config[16762]: Stack trace:
Oct 30 08:16:00 opnsense.home.arpa config[16762]: #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(688): OPNsense\Base\BaseModel->serializeToConfig()
Oct 30 08:16:00 opnsense.home.arpa config[16762]: #1 /usr/local/opnsense/mvc/script/run_migrations.php(55): OPNsense\Base\BaseModel->runMigrations()
Oct 30 08:16:00 opnsense.home.arpa config[16762]: #2 {main} )
```

**To Reproduce**
1. Install 21.7.3_3
2. Install `os-frr`
3. Configure a basic BGP  setup in FRR; do not configure OSPF, RIP
4. Upgrade to 21.7.4

**Expected behavior**
Upgrade proceeds cleanly with no migration errors

**Screenshots**

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 21.7.3_3 -> 21.7.4

**Comment by g-a-c** [comment]
I investigated a little more, it looks like this is probably not a new error; since Router ID is a required field for OSPFv3 and it makes no sense to configure RIP without a list of networks, these are set as required fields with no defaults in their respective config schema.

So I guess if you were actually using these features you would be forced to have a valid configuration per the schema, and the migrations would not fail, it's only an issue when you don't use these features in which case the failure doesn't matter because you don't need any configuration to be present anyway.
