### ISSUE TITLE
net/haproxy: No changes get applied to haproxy.conf

### ISSUE THREAD

**Issue by Technikte** [opnsense/plugins#2636]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
Configuration changes doenst get applied to the haproxy.conf, so no changes are possible.
The last changes before today were quite some time ago, so maybe the haproxy.conf shema changed ?

**To Reproduce**
1. Add some stuff through the web ui
2. Nothing get added and the backend doenst work
3. Error in log

**Expected behavior**
I cloned much older entries for real server and backend, changed them to my specif settings, they (the old ones) still works.

**Screenshots**

**Relevant log files**
`Inline action failed with OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf expected token ',', got 'integer' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 247, in _generate j2_page = self._j2_env.get_template(template_filename) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template return self._load_template(name, globals) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template template = self.loader.load(self, name, self.make_globals(globals)) File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load code = environment.compile(source, name, filename) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile self.handle_exception(source=source_hint) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/modules/../templates/OPNsense/HAProxy/haproxy.conf", line 136, in template {% set acl_enabled = '0' %} jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'integer' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 341, in generate raise render_exception File "/usr/local/opnsense/service/modules/template.py", line 332, in generate for filename in self._generate(template_name, create_directory): File "/u`

`Inline action failed with OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf expected token ',', got 'integer' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 247, in _generate j2_page = self._j2_env.get_template(template_filename) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template return self._load_template(name, globals) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template template = self.loader.load(self, name, self.make_globals(globals)) File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load code = environment.compile(source, name, filename) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile self.handle_exception(source=source_hint) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/modules/../templates/OPNsense/HAProxy/haproxy.conf", line 136, in template {% set acl_enabled = '0' %} jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'integer' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 341, in generate raise render_exception File "/usr/local/opnsense/service/modules/template.py", line 332, in generate for filename in self._generate(template_name, create_directory): File "/u`

**Additional context**
Example Screenshots, no backend "VaultwardenBackend" visible in Statistics
![image](https://user-images.githubusercontent.com/49494924/140644962-4727ac06-8570-47ef-9862-f2291659ca82.png)
![image](https://user-images.githubusercontent.com/49494924/140644996-03312ebc-9f29-4f57-8cc9-ef19f0c37257.png)

**Environment**
OPNsense 21.7.4-amd64
FreeBSD 12.1-RELEASE-p20-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by Technikte** [comment]
@fraenki I would like help or maybe the problem has already been fixed in the commits of the last days ?
Have a nice day. :)

**Comment by Technikte** [comment]
I am sorry, it seems it is a duplicate of https://github.com/opnsense/plugins/issues/2616 . Later I will try the patch that got mentioned, also close this isssue for now.
