### ISSUE TITLE
Nginx does not build nginx.conf

### ISSUE THREAD

**Issue by rudiservo** [opnsense/plugins#2683]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

[X] The title contains the plugin to which this issue belongs

**Describe the bug**
tried removing the conf file, reinstaling the plugin and changing options in the webpannel did not work.
The /usr/local/etc/nginx/nginx.conf does not build,

Haven't tried previous versions since this one has been working with my old conf for a long time.

**Relevant log files**
`
[5596fc48-8134-4095-beca-99826fe4358f] Inline action failed with OPNsense/Nginx OPNsense/Nginx/nginx.conf 'dict object' has no attribute 'server' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 267, in _generate content = j2_page.render(cnf_data) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render self.environment.handle_exception() File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/modules/../templates/OPNsense/Nginx/nginx.conf", line 27, in top-level template code {% include "OPNsense/Nginx/streams.conf" %} File "/usr/local/opnsense/service/modules/../templates/OPNsense/Nginx/streams.conf", line 19, in top-level template code server {% if ':' in upstream_server.server %}[{% endif %}{{ upstream_server.server }}{% if ':' in upstream_server.server %}]{% endif jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'server' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 344, in generate raise render_exception File "/usr/local/opnsense/service/modules/template.py", line 335, in generate for filename in self._generate(template_name, create_directory): File "/usr/local/opnsense/service/modules/template.py", line 270, in _generate raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense/Nginx OPNsense/Nginx/nginx.conf 'dic
`

**Environment**

OPNsense 21.7.6-amd64
FreeBSD 12.1-RELEASE-p21-HBSD
OpenSSL 1.1.1l 24 Aug 2021

**Comment by 8191** [comment]
@rudiservo Might it be that you've configured an upstream without upstream servers? In the upstream configuration you need to define servers *and* assign them to upstream. I.e. each configured upstream needs to have at least one server configured.

**Comment by rudiservo** [comment]
> @rudiservo Might it be that you've configured an upstream without upstream servers? In the upstream configuration you need to define servers _and_ assign them to upstream. I.e. each configured upstream needs to have at least one server configured.

you are right... somehow a upstream appeared again after I deleted it... strange.
Yeah closing this one. now having issues with HAPROXY... oh well... 
Thanks for your time and sorry...

**Comment by 8191** [comment]
@rudiservo This shouldn't be possible in the first place. The UI should prevent such an invalid configuration. Did you have an upstream without a server configured? 
Do you know any trigger for this issue to occur?

**Comment by rudiservo** [comment]
@8191 I think I deleted the upstream server first but left the upstream referencing to it, but this was in the process of debugging an issue with nginx and HAproxy that happen all of the sudden after upgrade and reboot.
