### ISSUE TITLE
os-freeradius - Bug report: 'collections.OrderedDict object' has no attribute 'ldap'

### ISSUE THREAD

**Issue by asherry99** [opnsense/plugins#2886]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Disclaimer... First time setting up opnsense, so if this is user error please feel free to close it.

When setting up freeradius and not using the ldap option, The following error seems to be generated. 

`
[6ccdc393-f3d4-4e0c-bcfb-3dfeaf5e9d6f] Inline action failed with OPNsense/Freeradius OPNsense/Freeradius/sites-enabled-inner-tunnel 'collections.OrderedDict object' has no attribute 'ldap' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 267, in _generate content = j2_page.render(cnf_data) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render self.environment.handle_exception() File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/modules/../templates/OPNsense/Freeradius/sites-enabled-inner-tunnel", line 158, in top-level template code {% if helpers.exists('OPNsense.freeradius.ldap.innertunnel') and OPNsense.freeradius.general.ldap.innertunnel == '1' %} File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr return getattr(obj, attribute) jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'ldap' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 344, in generate raise render_exception File "/usr/local/opnsense/service/modules/template.py", line 335, in generate for filename in self._generate(template_name, create_directory): File "/usr/local/opnsense/service/modules/template.py", line 270, in _generate raise Exception("%s %s %s" % (module_name, template_filename, render_exception)) Exception: OPNsense/Freeradius OPNsense/Freeradius/sites-enabled-inner-tunnel
`

It looks like some UI items make it into files like: `cat /usr/local/etc/raddb/clients.conf` but others like are empty `cat /usr/local/etc/raddb/users`

**To Reproduce**
Set up a basic free radius implementation w/ no LDAP options selected. See screenshots.

**Expected behavior**
I expect freeradius config files to be written on save.
<img width="1484" alt="Screen Shot 2022-03-07 at 6 22 04 PM" src="https://user-images.githubusercontent.com/77520/157153725-7de9a7e5-9e39-4b88-916c-d726e9cb8dd8.png">
<img width="1072" alt="Screen Shot 2022-03-07 at 6 27 42 PM" src="https://user-images.githubusercontent.com/77520/157154248-47de7dea-27dd-4265-85a8-52473ea82b95.png">
<img width="977" alt="Screen Shot 2022-03-07 at 6 26 03 PM" src="https://user-images.githubusercontent.com/77520/157154115-479c7c3b-fa79-4c16-a0f1-f37b26c3d7b9.png">
<img width="975" alt="Screen Shot 2022-03-07 at 6 25 40 PM" src="https://user-images.githubusercontent.com/77520/157154119-e61f9db1-d579-454a-868a-8af0c5e306b9.png">

**Relevant log files**
See Above.

**Additional context**
I posted about this in the Reddit Channel, someone else said they experienced to as well which leads me to hope it's a bug and not user error. https://www.reddit.com/r/opnsense/comments/t7mcau/running_in_to_error_inline_action_failed_with/

**Environment**
os-freeradius 1.9.19
 opnsense version ; Version 22.1.2_1; Architecture amd64; Flavour OpenSSL; Commit 80eff6d1e
Intel(R) Celeron(R) CPU J3160 @ 1.60GHz (4 cores, 4 threads)

**Comment by mimugmail** [comment]
Please check If this fixes it

https://github.com/opnsense/plugins/pull/2881#issuecomment-1060478797

**Comment by asherry99** [comment]
Thank you @mimugmail That fixed it!

Shoot, I don't know how I missed when I searched earlier 🤦🏻‍♂️
