### ISSUE TITLE
os-frr: daemon never starts

### ISSUE THREAD

**Issue by lerra** [opnsense/plugins#3175]
**Important notices**
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
The deamon is not running at all and giving error in the logs when the web gui is executing show commands and in the shell when running vtysh it says it failed to connect to the deamon. This was the first time I installed os-frr on my opnsense.

**To Reproduce**
1. Install the os-frr plugin and you will see an error in the output
```
***GOT REQUEST TO INSTALL***
Currently running OPNsense 22.7.6 (amd64/OpenSSL) at Tue Oct 25 23:53:04 CEST 2022
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 6 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	frr7: 7.5.1_4
	libssh: 0.10.4
	libyang: 1.0.240
	net-snmp: 5.9.1_1,1
	os-frr: 1.30
	rtrlib: 0.6.3

Number of packages to be installed: 6

The process will require 27 MiB more space.
[1/6] Installing libssh-0.10.4...
[1/6] Extracting libssh-0.10.4: .......... done
[2/6] Installing libyang-1.0.240...
[2/6] Extracting libyang-1.0.240: .......... done
[3/6] Installing rtrlib-0.6.3...
[3/6] Extracting rtrlib-0.6.3: .......... done
[4/6] Installing net-snmp-5.9.1_1,1...
[4/6] Extracting net-snmp-5.9.1_1,1: .......... done
[5/6] Installing frr7-7.5.1_4...
===> Creating groups.
Using existing group 'frr'.
Using existing group 'frrvty'.
===> Creating users
Using existing user 'frr'.
[5/6] Extracting frr7-7.5.1_4: .......... done
[6/6] Installing os-frr-1.30...
[6/6] Extracting os-frr-1.30: .......... done
Stopping configd...done
Starting configd.
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Quagga: OK
Reloading template OPNsense/Syslog: OK
=====
Message from net-snmp-5.9.1_1,1:

--
**** This port installs snmpd, header files and libraries but does not
     start snmpd by default.
     If you want to auto-start snmpd and snmptrapd:, add the following to
     /etc/rc.conf:

	snmpd_enable="YES"
	snmpd_flags="-a"
	snmpd_conffile="/usr/local/share/snmp/snmpd.conf /etc/snmpd.conf"
	snmptrapd_enable="YES"
	snmptrapd_flags="-a -p /var/run/snmptrapd.pid"

**** You may also specify the following make variables:

	NET_SNMP_SYS_CONTACT="zi@FreeBSD.org"
	NET_SNMP_SYS_LOCATION="USA"
	DEFAULT_SNMP_VERSION=3
	NET_SNMP_MIB_MODULES="host smux mibII/mta_sendmail ucd-snmp/diskio"
	NET_SNMP_LOGFILE=/var/log/snmpd.log
	NET_SNMP_PERSISTENTDIR=/var/net-snmp

     to define default values (or to override the defaults).  To avoid being
     prompted during the configuration process, you should (minimally) define
     the first two variables. (NET_SNMP_SYS_*)

     You may also define the following to avoid all interactive configuration:

	BATCH="yes"
=====
Message from frr7-7.5.1_4:

--
Beware that remote control of frr7 daemons over TCP sockets is enabled by
default.
Use daemon flags in /etc/rc.conf to disable it if unneeded, for example:
zebra_flags="-P0"
ospfd_flags="-P0"

FRR's OSPF daemons tries to allocate big socket buffer, so generate warning
messages like:
"setsockopt_so_sendbuf: fd 6: SO_SNDBUF set to 1048576 (requested 8388608)"
To prevent such message kern.ipc.maxsockbuf can be increased:
sysctl kern.ipc.maxsockbuf=16777216

Error message "ifam_read() doesn't read all socket data" is under investigation
Checking integrity... done (0 conflicting)
Nothing to do.
***DONE***
```
2. Go to routing -> bgp and enable
3. Go to routing -> diagnostics -> bgp and check each tab (they are empty/null)
4.  Go to system -> logfiles -> backend and you will see the following error(s)
```
 [93fe5dc1-x-4502-x-x] Script action failed with Command '/usr/local/bin/vtysh -c "show bgp ipv6 json" ' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 482, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/bin/vtysh -c "show bgp ipv6 json" ' returned non-zero exit status 1.
``
5. ssh to opnsense and run the following in the shell ```vtysh``` and you will get the following error: Exiting: failed to connect to any daemons.

**Expected behavior**
To have the deamon running so you can see the bgp state, no errors in the logs and you should be able to run vtysh in the shell.

**Additional context**
This is the first time I installed the package, I have not configured anything besides bgp, 

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q 5 Jul 2022

**Comment by mimugmail** [comment]
Did you enable the whole routing daemon in General menu?

**Comment by lerra** [comment]
@mimugmail Hi mate,

You made my day!

It was really hard to find some good documentation and I could not see that I needed to enable some generic routing in https://docs.opnsense.org/manual/how-tos/dynamicrouting_bgp.htm, at the same time it is stated in https://docs.opnsense.org/manual/dynamic_routing.html#general-setup but no documentation connection to the above bgp documentation so I could not understand the dependency.  Would it make sense to do that connection between the documentation or automatically enable the generic daemon when enabling a dynamic routing daemon such as bgp?

But once again, big thanks!

**Comment by williamdes** [comment]
Thank you !
You made my day too !
