### ISSUE TITLE
mail/rspamd: template error after fresh install

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#353]
```
Oct 31 06:23:11 OPNsense pkg: fann-2.2.0 installed
Oct 31 06:23:12 OPNsense pkg: luajit-2.0.5 installed
Oct 31 06:23:12 OPNsense pkg: glib-2.50.2_6,1 installed
Oct 31 06:23:12 OPNsense pkg: rspamd-1.6.5 installed
Oct 31 06:23:13 OPNsense configd.py: [62a7b5a9-1eb0-4148-a00d-64096d90c1fc] request pfctl byte/packet counters
Oct 31 06:23:16 OPNsense configd.py Stopping daemon.
Oct 31 06:23:16 OPNsense configd.py Starting daemon.
Oct 31 06:23:17 OPNsense configd.py: [0f558658-5597-4493-8dfb-29f786e5622b] generate template OPNsense/Rspamd
Oct 31 06:23:18 OPNsense configd.py: generate template container OPNsense/Rspamd
Oct 31 06:23:18 OPNsense configd.py: [0f558658-5597-4493-8dfb-29f786e5622b] Inline action failed with OPNsense/Rspamd OPNsense/Rspamd/mx_check.conf 'collections.OrderedDict object' has no attribute 'Rspamd' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 507, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 309, in generate     raise render_exception Exception: OPNsense/Rspamd OPNsense/Rspamd/mx_check.conf 'collections.OrderedDict object' has no attribute 'Rspamd'
Oct 31 06:23:18 OPNsense pkg: os-rspamd-devel-0.1 installed

```

Perhaps some wrong defaults? Havent digged into it yet.

**Comment by fabianfrz** [comment]
No, probably not saved the file and I have not added a default value or a lock. I'll add a fix for that.

**Comment by mimugmail** [comment]
Closed, thanks 👍

**Comment by fabianfrz** [comment]
@mimugmail everything ok now?

**Comment by mimugmail** [comment]
Yes. 
Why is openfish premium enabled by default?

**Comment by fabianfrz** [comment]
maybe a copying issue

**Comment by fabianfrz** [comment]
@mimugmail this was disabled - maybe something went wrong:
https://github.com/opnsense/plugins/blob/master/mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml#L126

**Comment by mimugmail** [comment]
Model is missing a field type

**Comment by fabianfrz** [comment]
which one?

**Comment by mimugmail** [comment]
The link you posted before?

**Comment by fabianfrz** [comment]
thanks - fixed: https://github.com/opnsense/plugins/commit/7d91e49d4087ad372e1f2af0c12015f1bcbe65b4
