### ISSUE TITLE
HAProxy fails to start after update to OPNsense 24.1.a_435-amd64

### ISSUE THREAD

**Issue by syberx** [opnsense/plugins#3660]
I have encountered an issue with OPNsense where, after updating to version 24.1.a_435-amd64 on FreeBSD 13.2-RELEASE-p3 with OpenSSL 1.1.1w dated 11 Sep 2023, the HAProxy service no longer starts. The error log is not providing much insight beyond the following message:

"2023-11-08T15:53:07 Error configd.py [b6bb0201-3178-4976-b53f-5903c3c98051] Script action failed with Command '/usr/local/opnsense/scripts/OPNsense/HAProxy/syncCerts.py actions --output bootgrid --page-rows '10' --page '1' --search '' --sort-col '' --sort-dir ''' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/actions/script_output.py", line 44, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/OPNsense/HAProxy/syncCerts.py actions --output bootgrid --page-rows '10' --page '1' --search '' --sort-col '' --sort-dir ''' returned non-zero exit status 1."

This error arises when attempting to execute the HAProxy syncCerts.py script. I haven't made any changes to the HAProxy configuration itself before or after the update. I'm currently at a loss for what steps to take to troubleshoot this issue further and would greatly appreciate any guidance or suggestions on how to resolve this error.

**Comment by syberx** [comment]
close
