### ISSUE TITLE
www/squid - UT1 blacklist not showing category

### ISSUE THREAD

**Issue by gobiursus** [opnsense/plugins#4392]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X ] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

I was following this tutorial to set up web filtering on my OPNsense instance: https://docs.opnsense.org/manual/how-tos/proxywebfilter.html
But UT1 blacklist is not showing any category after I successfully download and apply the list.
Please help!

**Expected behavior**
Show the categorizes

**Environment**
Software version used and hardware type if relevant.

OPNsense 24.7.10_2-amd64
QEMU Virtual CPU version 2.5+ (4 cores, 4 threads)
Network Mellanox ConnectX-3

**Comment by vnguyen1** [comment]
Yes, I have the same issue here.
And now, when I enable the Remote Blacklist UT1, I can't start the Proxy Service.
Error Code:

Starting squid.
CPU Usage: 4.279 seconds = 4.201 user + 0.079 sys
Maximum Resident Size: 1317024 KB
Page faults with physical i/o: 0
2024/12/11 16:08:15| Processing Configuration File: /usr/local/etc/squid/squid.conf (depth 0)
2024/12/11 16:08:15| Starting Authentication on port 127.0.0.1:3128
2024/12/11 16:08:15| Disabling Authentication on port 127.0.0.1:3128 (interception enabled)
2024/12/11 16:08:15| Starting Authentication on port [::1]:3128
2024/12/11 16:08:15| Disabling Authentication on port [::1]:3128 (interception enabled)
2024/12/11 16:08:15| Starting Authentication on port 127.0.0.1:3129
2024/12/11 16:08:15| Disabling Authentication on port 127.0.0.1:3129 (interception enabled)
2024/12/11 16:08:15| Starting Authentication on port [::1]:3129
2024/12/11 16:08:15| Disabling Authentication on port [::1]:3129 (interception enabled)
2024/12/11 16:08:19| ERROR: '.ai-nude.adult' is a subdomain of '.adult'
2024/12/11 16:08:19| ERROR: You need to remove '.ai-nude.adult' from the ACL named 'remoteblacklist_UT1'
2024/12/11 16:08:19| Not currently OK to rewrite swap log.
2024/12/11 16:08:19| storeDirWriteCleanLogs: Operation aborted.
2024/12/11 16:08:19| FATAL: Bungled /usr/local/etc/squid/squid.conf line 56: acl remoteblacklist_UT1 dstdomain "/usr/local/etc/squid/acl/UT1"
2024/12/11 16:08:19| Squid Cache (Version 6.10): Terminated abnormally.
/usr/local/etc/rc.d/squid: WARNING: failed to start squid

**Comment by droumanet** [comment]
Confirmed here too.
A (weird) workaround is to create multiples lists one by one.
![image](https://github.com/user-attachments/assets/ee47e9b6-55b0-4025-8edc-336fbe0d640f)

By the way, what are requirement for using these functionalities? My FW become unable to pass any frame after a few moment and RAM seems 90% busy in dashboard.
My hardware is 12GB RAM, 250GB disk and Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 cores, 4 threads)

**Comment by AUSK1LL9** [comment]
Can confirm, I am having the same issue. However I can not get any list to work. Even simplified list like cooking or adult. I have tried FTp HHTTPS. Recycled service, deleted and remade. Removed and re-added os-squid plugin. Same issue.
squid-6.12
OPNsense 24.7.11_2-amd64
FreeBSD 14.1-RELEASE-p6
OpenSSL 3.0.15

![image](https://github.com/user-attachments/assets/938e4867-9f7a-4ebf-b83a-aff7ede63ef6)

**Comment by droumanet** [comment]
I can use university of Toulouse list... but on OPNSense 24.1 version.
Problem occurs with version 24.7.x
**Is there a regression?**

**Comment by AdSchellevis** [comment]
Could be the size of the list, easiest way to debug this is by using the script manually (`/usr/local/opnsense/scripts/proxy/fetchACLs.py`)

By the way, the `OPNProxy` plugin uses the same list but has a better approach in handling the contents, static lists within squid have strict sorting requirements which is one of the main bottlenecks in this feature.

**Comment by w9hdg** [comment]
I just tried calling the script manually, it ran for a minute or two before exiting with no output.

**Comment by gobiursus** [comment]
Please fix this issue in next release!

**Comment by AdSchellevis** [comment]
feel free to open a pull request if there's anything to fix....

**Comment by droumanet** [comment]
> /usr/local/opnsense/scripts/proxy/fetchACLs.py

Thanks for the tips. On my firewall, I've got a full page of errors.
`/usr/local/opnsense/scripts/proxy/fetchACLs.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x241749633450>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dsi.ut-capitole.fr', port=80): Max retries exceeded with url: /blacklists/download/games.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x241749633450>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/proxy/fetchACLs.py", line 381, in <module>
    main()
  File "/usr/local/opnsense/scripts/proxy/fetchACLs.py", line 325, in main
    for filename, basefilename, file_ext, line in acl.download():
  File "/usr/local/opnsense/scripts/proxy/fetchACLs.py", line 153, in download
    self.fetch()
  File "/usr/local/opnsense/scripts/proxy/fetchACLs.py", line 83, in fetch
    req = requests.get(**req_opts)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='dsi.ut-capitole.fr', port=80): Max retries exceeded with url: /blacklists/download/games.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x241749633450>: Failed to establish a new connection: [Errno 61] Connection refused'))
`
What should I do to help more?

**Comment by AdSchellevis** [comment]
@droumanet looks like `dsi.ut-capitole.fr` is unreachable, from here I also can't reach their location.

**Comment by debtodevnull** [comment]
The UT1 blacklist seems reachable again and the issue is still there (using OPNSense 24.7.11_2) :  

![image](https://github.com/user-attachments/assets/3485f8a6-4abb-401d-8890-d560ce4978e7)

**Comment by abonanni** [comment]
+1

**Comment by gobiursus** [comment]
> 👍
> 
> Categories are generated in `/usr/local/etc/squid/acl/UT.index` :
> 
> ```
> {"adult": "adult", "agressif": "agressif", "arjel": "arjel", "astrology": "astrology", "audio-video": "audio-video", "bank": "bank", "bitcoin": "bitcoin", "blog": "blog", "celebrity": "celebrity", "chat": "chat", "child": "child", "cleaning": "cleaning", "cooking": "cooking", "dangerous_material": "dangerous_material", "dating": "dating", "dialer": "dialer", "drogue": "drogue", "educational_games": "educational_games", "filehosting": "filehosting", "financial": "financial", "forums": "forums", "gambling": "gambling", "games": "games", "hacking": "hacking", "jobsearch": "jobsearch", "lingerie": "lingerie", "liste_blanche": "liste_blanche", "liste_bu": "liste_bu", "malware": "malware", "manga": "manga", "marketingware": "marketingware", "mixed_adult": "mixed_adult", "mobile-phone": "mobile-phone", "phishing": "phishing", "press": "press", "publicite": "publicite", "radio": "radio", "reaffected": "reaffected", "redirector": "redirector", "remote-control": "remote-control", "sect": "sect", "sexual_education": "sexual_education", "shopping": "shopping", "social_networks": "social_networks", "sports": "sports", "strict_redirector": "strict_redirector", "strong_redirector": "strong_redirector", "translation": "translation", "tricheur": "tricheur", "warez": "warez", "webmail": "webmail", "special": "special", "download": "download", "ddos": "ddos", "update": "update", "associations_religieuses": "associations_religieuses", "shortener": "shortener", "cryptojacking": "cryptojacking", "exceptions_liste_bu": "exceptions_liste_bu", "vpn": "vpn", "stalkerware": "stalkerware", "doh": "doh", "examen_pix": "examen_pix", "tricheur_pix": "tricheur_pix", "residential-proxies": "residential-proxies", "fakenews": "fakenews"}
> ```
> 
> But no category is available in web interface.

You are right, no categorize on web interface.

**Comment by AdSchellevis** [comment]
probably this https://github.com/opnsense/core/issues/8180

**Comment by baka0taku2022** [comment]
A temporary fix for this is to delete the offending line from the /usr/local/etc/squid/acl/UTI file. I used vim. (`pkg install vim`)

`vim /usr/local/etc/squid/acl/UTI`

use the `/` command to search for `.ai-nude.adult`

`/.ai-nude.adult` and press Enter.

use `dd` to delete the line.

Type `:wq` to save.

Start Squid from the web GUI.

**Comment by sjjh** [comment]
I'm also still facing the issue, that the categories drop-down in the Web UI is empty. I did run `fetchACLs.py` without any output (thus I assume without any errors). I'm running OPNSense 25.7.2, thus I assume https://github.com/opnsense/core/issues/8180 should be included already. Any other idea how to solve it or debug further?
(*Note:* Use case over here is category based filtering of the traffic with whitelisting of IP addresses (no user authentication) with transparent proxy and SNI; thus I'm not sure if *OPNProxy* is a valid alternative.)

**Comment by droumanet** [comment]
I could not reopen this issue, but it should be checked.

**Comment by gobiursus** [comment]
> I'm also still facing the issue, that the categories drop-down in the Web UI is empty. I did run `fetchACLs.py` without any output (thus I assume without any errors). I'm running OPNSense 25.7.2, thus I assume [opnsense/core#8180](https://github.com/opnsense/core/issues/8180) should be included already. Any other idea how to solve it or debug further? (_Note:_ Use case over here is category based filtering of the traffic with whitelisting of IP addresses (no user authentication) with transparent proxy and SNI; thus I'm not sure if _OPNProxy_ is a valid alternative.)

@droumanet Wait, the same issue come back again?

**Comment by sjjh** [comment]
@gobiursus at least for me it's still unsolved as described above, not sure how the situation is for @droumanet

**Comment by droumanet** [comment]
Seems to be the same. But unable to help to troubleshoot it.

**Comment by sjjh** [comment]
@AdSchellevis would you mind re-opening the issue, or what's the best approach to progress forward?

**Comment by AdSchellevis** [comment]
when someone opens a PR or there's a clear owner of the issue we can reopen the ticket. squid is community support scope.

**Comment by sjjh** [comment]
I'm not even sure if it is a squid issue, or caused by changing the UI table framework.
Anyhow, what is the currently recommended solution to use category based web filtering? If I understand the [docs](https://docs.opnsense.org/manual/how-tos/proxywebfilter.html) correctly, it's still squid?

**Comment by alfonsrv** [comment]
Got the same issue on `25.7.2` + `os-squid` `1.2_3` for `ftp://ftp.ut-capitole.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz`

First running into a timeout via GUI and when manually executing the Python file the index file generates as expected. 

<details>
  <summary>Timeout log</summary>

```
==> /var/log/configd/latest.log <==
<147>1 2025-09-04T20:24:41+00:00 OPNsense.internal configd.py 87499 - [meta sequenceId="1"] Timeout (120) executing : proxy fetchacls
```

</details>


<details>
  <summary>Executing fetchACLs.py manually</summary>

Added some debug printing in the Python script:

```
root# date ; /usr/local/opnsense/scripts/proxy/fetchACLs.py ; date
Thu Sep  4 19:56:45 UTC 2025

FTP downloading ftp://ftp.ut-capitole.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz
Extracting: blacklists/README
Extracting: blacklists/global_usage
Extracting: blacklists/cc-by-sa-4-0.pdf
Extracting: blacklists/LICENSE.pdf
Extracting: blacklists/adult/domains
Extracting: blacklists/adult/expressions
Extracting: blacklists/adult/urls
...
Extracting: blacklists/webhosting/urls
Extracting: blacklists/ai/domains
Extracting: blacklists/ai/usage

Thu Sep  4 20:04:54 UTC 2025
```

</details>




<details>
  <summary>Output ut1.index</summary>

```
root# cat squid/acl/ut1.index 
{"adult": "adult", "agressif": "agressif", "arjel": "arjel", "astrology": "astrology", "audio-video": "audio-video", "bank": "bank", "bitcoin": "bitcoin", "blog": "blog", "celebrity": "celebrity", "chat": "chat", "child": "child", "cleaning": "cleaning", "cooking": "cooking", "dangerous_material": "dangerous_material", "dating": "dating", "dialer": "dialer", "drogue": "drogue", "educational_games": "educational_games", "filehosting": "filehosting", "financial": "financial", "forums": "forums", "gambling": "gambling", "games": "games", "hacking": "hacking", "jobsearch": "jobsearch", "lingerie": "lingerie", "liste_blanche": "liste_blanche", "liste_bu": "liste_bu", "malware": "malware", "manga": "manga", "marketingware": "marketingware", "mixed_adult": "mixed_adult", "mobile-phone": "mobile-phone", "phishing": "phishing", "press": "press", "publicite": "publicite", "radio": "radio", "reaffected": "reaffected", "redirector": "redirector", "remote-control": "remote-control", "sect": "sect", "sexual_education": "sexual_education", "shopping": "shopping", "social_networks": "social_networks", "sports": "sports", "strict_redirector": "strict_redirector", "strong_redirector": "strong_redirector", "translation": "translation", "tricheur": "tricheur", "warez": "warez", "webmail": "webmail", "special": "special", "download": "download", "ddos": "ddos", "update": "update", "associations_religieuses": "associations_religieuses", "shortener": "shortener", "cryptojacking": "cryptojacking", "exceptions_liste_bu": "exceptions_liste_bu", "vpn": "vpn", "stalkerware": "stalkerware", "doh": "doh", "examen_pix": "examen_pix", "tricheur_pix": "tricheur_pix", "residential-proxies": "residential-proxies", "fakenews": "fakenews", "dynamic-dns": "dynamic-dns", "webhosting": "webhosting", "ai": "ai"}
```

</details>

The categories in the GUI are empty though. It worked a month or two ago – albeit on slightly more potent hardware.

edit: Got this when running `squid -k reconfigure`:
`2025/09/04 20:50:17| FATAL: Bungled /usr/local/etc/squid/squid.conf line 56: acl remoteblacklist_ut1 dstdomain "/usr/local/etc/squid/acl/ut1"`


```
root#  head -58 /usr/local/etc/squid/acl/ut1
...
.name ru: сексуальное образование.
.name ru: перевод.
.name ru: очистка, антивирусы и т. д.
```

**Comment by sjjh** [comment]
On inspecting this further, it seems that for me over here the category based blocking itself by the block list in squid still works and it is *only* a "cosmetic" problem, not showing the categories in the web GUI. This strengths my hypothesis, that after all it might not be related to squid, but to the changes in the MVC table design. @AdSchellevis does this sound plausible?

**Comment by AdSchellevis** [comment]
> Anyhow, what is the currently recommended solution to use category based web filtering? If I understand the [docs](https://docs.opnsense.org/manual/how-tos/proxywebfilter.html) correctly, it's still squid?

Unbound when only filtering the dns request parts, otherwise Zenarmor might be a better alternative to look at as squid on our end is community support only.

> ...not showing the categories in the web GUI. This strengths my hypothesis, that after all it might not be related to squid, but to the changes in the MVC table design. @AdSchellevis does this sound plausible?

That could be the case, I'm not using squid myself, but if someone opens a PR to fix an issue, I'll take a look.

**Comment by oulra** [comment]
```xml
<filter type="JsonKeyValueStoreField">              
	<SourceField>filename</SourceField>             
	<SourceFile>/usr/local/etc/squid/acl/%s.index</SourceFile>
	<SelectAll>Y</SelectAll>                        
	<Multiple>Y</Multiple>                          
</filter>
```
It's seems to be related to `internalSourceField` attribute not being initialized:

adding line `$this->setSourceField("filename");`  in `mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php` make blacklist category showing up:

```php:mvc/app/models/OPNsense/Base/FieldTypes/JsonKeyValueStoreField.php
125     protected function actionPostLoadingEvent()                                 
126     {                                                                           
127         $data = null;                                                           
128         $this->setSourceField("filename");                                      
129         if ($this->internalSourceFile != null && $this->internalSourceField != null) {
130             $sourcefile = sprintf($this->internalSourceFile, $this->internalSourceField);
131         } else {                                                                
132             $sourcefile = $this->internalSourceFile;                            
133         } 
```

`cp /usr/local/etc/squid/acl/UT1.index /usr/local/etc/squid/acl/%s.index` can be used as a workaround
