### ISSUE TITLE
plugin install causes templates to fail

### ISSUE THREAD

**Issue by fichtner** [opnsense/plugins#53]
Hi Ad, this isn't severe, but I think we should keep track of this. Installed all plugins at once on a fresh 16.7.8 and it gave me the following errors:
```
Nov 15 15:26:21	configd.py: [1a459910-41df-408a-8c17-9439741483d4] Inline action failed with OPNsense/Tinc OPNsense/Tinc/tinc_deploy.xml 'NoneType' object has no attribute '__getitem__' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 52, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 308, in generate raise render_exception Exception: OPNsense/Tinc OPNsense/Tinc/tinc_deploy.xml 'NoneType' object has no attribute '__getitem__'
Nov 15 15:24:48	configd.py: [4ba75234-bf0b-4000-a785-fac8860cc9a2] Inline action failed with OPNsense/HelloWorld OPNsense/HelloWorld/helloworld.conf 'collections.OrderedDict object' has no attribute 'helloworld' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 52, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 308, in generate raise render_exception Exception: OPNsense/HelloWorld OPNsense/HelloWorld/helloworld.conf 'collections.OrderedDict object' has no attribute 'helloworld'
Nov 15 15:23:57	configd.py: [c8538f17-c3de-4152-822a-9cee9a25c264] Inline action failed with OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf 'collections.OrderedDict object' has no attribute 'HAProxy' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 52, in execute filenames = tmpl.generate(parameters) File "/usr/local/opnsense/service/modules/template.py", line 308, in generate raise render_exception Exception: OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf 'collections.OrderedDict object' has no attribute 'HAProxy'
```

**Comment by fichtner** [comment]
Sorry, tinc had a suboptimal config due to a previous import. With a clean config tinc installs fine.

**Comment by AdSchellevis** [comment]
ok, nice, can we close this issue then?

**Comment by fichtner** [comment]
no, haproxy and helloworld are not perfectly fine, the first thing the user sees is an error during install. it's probably just a guard missing in the templates. I'll look into it.

**Comment by fraenki** [comment]
Regarding HAProxy: I could wrap the whole `haproxy.conf` template in a `{% if helpers.exists('OPNsense.HAProxy') %}` clause if this is the way to go. :)

**Comment by fichtner** [comment]
Yes and no. We need standards hooks for migrations during plugin install that could take care of this, then fix the model, if that is indeed a sensible approach. Not sure yet.

**Comment by fichtner** [comment]
OPNsense/HAProxy OPNsense/HAProxy/haproxy.conf 'collections.OrderedDict object' has no attribute 'HAProxy'

Still there with a vanilla install of 17.7-RC1

**Comment by fraenki** [comment]
@fichtner Should I add the previously mentioned if-clause to the HAProxy template?

**Comment by fichtner** [comment]
@fraenki that would be helpful, I can do the testing
