### ISSUE TITLE
WAN DHCPv4 gives up after few minutes and comes never again up

### ISSUE THREAD

**Issue by goor4** [opnsense/plugins#584]
Situation:
- Actual Version of OPNsense 
- Cisco-Cable Modem
- IPv4 Internet via DHCP

Wenn Cable-Modem lost link, it keeps rebooting and WAN-Ethernet-Link goes up and down.
If the network-problem  of the internet provider is repaired within some minutes, everything is ok.

But if the provider problem last more than ca 10 minutes, the dhcp-Client on WAN from OPNsense gives up and internet connection stays down until manual intervention/renew in WEB-GUI.

Here the chronology:
## Cable Modem lost Sync, reboots
Mar 5 08:55:21 	kernel: igb1: link state changed to DOWN
Mar 5 08:55:21 	configd.py: [7e29785b-20d7-416a-8f12-fa4bdfb85d41] Linkup stopping igb1
Mar 5 08:55:22 	opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet detached event for wan
Mar 5 08:55:22 	opnsense: /usr/local/etc/rc.linkup: Clearing states to old gateway 109.91.104.1.

## Cable Modem link comes up again
Mar 5 08:55:41 	kernel: igb1: link state changed to UP
Mar 5 08:55:41 	configd.py: [434f0198-6edb-441d-a6c1-fa097bd702b0] Linkup starting igb1
Mar 5 08:55:42 	opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet attached event for wan
Mar 5 08:55:42 	opnsense: /usr/local/etc/rc.linkup: HOTPLUG: Configuring interface wan
Mar 5 08:55:46 	opnsense: /usr/local/etc/rc.newwanip: On (IP address: 192.168.100.10) (interface: WAN[wan]) (real interface: igb1).
Mar 5 08:55:46 	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1'

## OPNSense get's private IP, because Cable-Modem has no sync 
Mar 5 08:55:47 	opnsense: /usr/local/etc/rc.newwanip: ROUTING: setting IPv4 default route to 192.168.100.1

Mar 5 08:55:57 	opnsense: /usr/local/etc/rc.newwanip: Aborted IP detection: Resolving timed out after 5689 milliseconds
Mar 5 08:57:04 	opnsense: /usr/local/etc/rc.dyndns: Aborted IP detection: Resolving timed out after 5628 milliseconds
Mar 5 08:57:05 	opnsense: /usr/local/etc/rc.newwanip: Aborted IP detection: Resolving timed out after 5630 milliseconds
Mar 5 08:57:41 	configd_ctl.py: error in configd communication Traceback (most recent call last): File "/usr/local/opnsense/service/configd_ctl.py", line 65, in exec_config_cmd line = sock.recv(65536) timeout: timed out

## Next Reboot of Cablemodem and get's private IP
Mar 5 08:58:11 	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1'
Mar 5 08:58:11 	opnsense: /usr/local/etc/rc.newwanip: On (IP address: 192.168.100.10) (interface: WAN[wan]) (real interface: igb1).

## PROBLEM: DHCP-Renew gives up:
Mar 5 08:58:51 	kernel: igb1: link state changed to UP
Mar 5 08:58:51 	configd.py: [d1ad4663-1ccd-4997-a240-7c4d9777e122] Linkup starting i
Mar 5 08:58:51 	opnsense: /usr/local/etc/rc.linkup: DEVD Ethernet attached event for wan
Mar 5 08:58:51 	opnsense: /usr/local/etc/rc.linkup: HOTPLUG: Configuring interface wan
Mar 5 08:58:52 	opnsense: /usr/local/etc/rc.linkup: The command '/sbin/dhclient -c /var/etc/dhclient_wan.conf igb1 > /tmp/igb1_output 2> /tmp/igb1_error_output' returned exit code '1', the output was ''
Mar 5 08:59:23 	configd.py: unable to sendback response [OK ] for [interface][linkup][['start', 'igb1']] {434f0198-6edb-441d-a6c1-fa097bd702b0}, message was Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run self.connection.sendall('%s\n' % result) File "/usr/local/lib/python2.7/socket.py", line 228, in meth return getattr(self._sock,name)(*args) error: [Errno 32] Broken pipe

##

## DHCP was down, klick on "renew"
Mar 5 19:41:20 	opnsense: /index.php: Successful login for user 'root' from: 192.168.33.162
Mar 5 19:42:02 	opnsense: /usr/local/etc/rc.newwanip: IP renewal is starting on 'igb1'
Mar 5 19:42:02 	opnsense: /usr/local/etc/rc.newwanip: On (IP address: 109.91.xx.yy) (interface: WAN[wan]) (real interface: igb1).
...

**Comment by goor4** [comment]
Wrong component, will reopen it in "core".
