### ISSUE TITLE
www/nginx: configd errors

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#816]
When installing latest master I get:

```
Sep  4 13:05:45 OPNsense configd.py: [78d27812-38ba-4340-a3f6-909ab597a0e1] Inline action failed with OPNsense/Nginx OPNsense/Nginx/nginx.conf 'None' has no attribute '@uuid' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 509, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 332, in generate     raise render_exception Exception: OPNsense/Nginx OPNsense/Nginx/nginx.conf 'None' has no attribute '@uuid'
Sep  4 13:05:50 OPNsense configd.py: [4f0a6fef-b9d3-4b69-8285-95b6cb4bc712] request pfctl byte/packet counters

```

Also happens with every save ...

**Comment by fabianfrz** [comment]
@mimugmail now you know why I hate the exception message. If I would not know that this is in my latest code, (because the earlier works different), I would have absolutely no idea where the exception is exactly thrown from the message…

**Comment by mimugmail** [comment]
Same same .. that's why I always make a make upgrade after every commit :)

**Comment by fabianfrz** [comment]
@mimugmail do you have time for IRC?
