### ISSUE TITLE
os-igmp-proxy - crash with 18.7.7 / igmpproxy not working

### ISSUE THREAD

**Issue by rx-tx** [opnsense/plugins#997]
I am running OPNsense 18.7.7 with os-igmp-proxy-1.3_1 for IPTV service.
The plugin was already running with 18.7.7 but since today i got a problem notification in the dashboard ("Unfortunately we have detected at least one programming bug.").
Service is no longer working and cannot be restarted.

Maybe it is because of the patch in 18.7.6 ( interfaces: replace get_configured_interface_list() usage).

PHP errors:

[18-Nov-2018 20:08:19 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function get_configured_interface_list() in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc:80
Stack trace:
#0 /usr/local/etc/inc/plugins.inc(213): igmpproxy_configure_do(true)
#1 /usr/local/etc/rc.bootup(118): plugins_configure('bootup', true)
#2 {main}
  thrown in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc on line 80
[18-Nov-2018 20:10:04 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function get_configured_interface_list() in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc:80
Stack trace:
#0 /usr/local/etc/inc/services.inc(1963): igmpproxy_configure_do()
#1 /usr/local/www/status_services.php(45): service_control_start('igmpproxy', Array)
#2 {main}
  thrown in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc on line 80
[18-Nov-2018 20:10:44 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function get_configured_interface_list() in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc:80
Stack trace:
#0 /usr/local/etc/inc/services.inc(1963): igmpproxy_configure_do()
#1 /usr/local/www/status_services.php(45): service_control_start('igmpproxy', Array)
#2 {main}
  thrown in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc on line 80
[18-Nov-2018 20:10:54 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function get_configured_interface_list() in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc:80
Stack trace:
#0 /usr/local/etc/inc/services.inc(1963): igmpproxy_configure_do()
#1 /usr/local/www/status_services.php(45): service_control_start('igmpproxy', Array)
#2 {main}
  thrown in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc on line 80
[18-Nov-2018 20:11:16 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function get_configured_interface_list() in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc:80
Stack trace:
#0 /usr/local/etc/inc/services.inc(1963): igmpproxy_configure_do()
#1 /usr/local/www/status_services.php(45): service_control_start('igmpproxy', Array)
#2 {main}
  thrown in /usr/local/etc/inc/plugins.inc.d/igmpproxy.inc on line 80

Kind regards!

**Comment by fichtner** [comment]
@rx-tx hi there, reinstalling the plugin should fix it. I forgot to bump the revision so it wasn't updated with 18.7.x when it should have. Will fix for 18.7.8. :)

**Comment by fichtner** [comment]
See https://github.com/opnsense/plugins/commit/6b6c0d0 -- please close if that was indeed the issue.

**Comment by rx-tx** [comment]
@fichtner: Re-installhing the plugin helped. Thanks a lot for your fast support :)

**Comment by fichtner** [comment]
super, thanks! 18.7.8 is planned for Thursday to fix it automatically on update for everyone else. :)
